import json

from app.models.state import ResearchState
from app.services.llm import get_llm
from app.services.llm_usage import extract_usage


def build_synthesis_evidence(
    state: ResearchState,
) -> str:
    """Build a compact evidence context for report generation."""

    sections = []

    # ------------------------------------------------------------
    # RAG evidence
    # ------------------------------------------------------------

    for document in state.retrieved_documents:

        company = document.get(
            "company_name",
            "",
        )

        if not company:
            continue

        content = document.get(
            "content",
            "",
        ).strip()

        content = content[:1800]

        sections.append(
            f"COMPANY: {company}\n"
            f"TITLE: {document.get('source_title', '')}\n"
            f"EVIDENCE TYPE: "
            f"{document.get('evidence_type', 'general')}\n"
            f"VERIFICATION STATUS: RAG_INDEXED\n"
            f"EVIDENCE: {content}\n"
            f"URL: {document.get('source_url', '')}"
        )

    # ------------------------------------------------------------
    # Direct research evidence
    # ------------------------------------------------------------

    for source in state.verified_sources:

        company = source.get(
            "company",
            source.get("company_name", ""),
        )

        if not company:
            continue

        content = source.get(
            "content",
            "",
        ).strip()

        content = content[:1800]

        verification_status = source.get(
            "verification_status",
            "unknown",
        )

        sections.append(
            f"COMPANY: {company}\n"
            f"TITLE: {source.get('title', '')}\n"
            f"EVIDENCE TYPE: "
            f"{source.get('evidence_type', 'general')}\n"
            f"VERIFICATION STATUS: "
            f"{verification_status}\n"
            f"EVIDENCE: {content}\n"
            f"URL: {source.get('url', '')}"
        )

    return "\n\n".join(sections)


def synthesizer_node(
    state: ResearchState,
) -> dict:
    """Generate the final research report."""

    if not state.company_scores:

        print(
            "No company scores available "
            "for synthesis."
        )

        return {
            "final_report": ""
        }

    print()
    print(
        "===== SYNTHESIZER INPUT SCORES ====="
    )

    for score in state.company_scores:

        print(
            f"{score.get('company_name')}: "
            f"{score.get('overall_score')}"
        )

    print(
        "====================================="
    )

    evidence_text = build_synthesis_evidence(
        state
    )

    companies_text = json.dumps(
        state.company_scores,
        indent=2,
    )

    prompt = f"""
Create a concise evidence-based research
report about the Indian AI startup market.

COMPANY SCORES:
{companies_text}

EVIDENCE:
{evidence_text}

CONFIDENCE SCORE:
{state.confidence_score}

IMPORTANT EVIDENCE RULES:

- Use ONLY the supplied scores and evidence.
- Do not add outside facts.
- Do not change any overall_score.
- Preserve the exact company names and scores.
- Do not invent funding, customers, revenue,
  products, partnerships, market size, or
  other facts.
- If a fact is not supported by evidence,
  explicitly say that the evidence is
  unavailable.
- RAG_INDEXED evidence is derived from the
  research database and is NOT independent
  verification.
- verification_status="verified" means the
  source passed the source verification step.
- verification_status="demo" means the source
  is synthetic fallback data and must NOT be
  described as real-world verified evidence.
- verification_status="unverified" means the
  source was not independently verified.
- Do not describe demo evidence as real
  research.
- Do not describe RAG documents as independent
  sources.
- Clearly reflect the confidence score.
- If confidence is 0.0, state that no genuinely
  verified web evidence was available.
- Do not claim that the market analysis is
  comprehensive when evidence is limited.

SCORE INTERPRETATION:

The overall_score is an evidence-adjusted
score generated by the scoring agent.

It is NOT a simple average across all six
categories.

Categories without supporting evidence
receive zero, and the score is adjusted
according to the number of categories
supported by evidence.

Do not recalculate the scores.

REPORT REQUIREMENTS:

The methodology must explain that:

1. Companies were evaluated using supplied
   evidence.

2. Six scoring categories were considered:
   funding, product, customer traction,
   growth, market opportunity, and
   competitive differentiation.

3. Unsupported categories receive zero.

4. The final overall score is evidence-adjusted
   based on supported categories.

5. Source verification and confidence are
   tracked separately.

The limitations section should mention
limitations that are actually supported by
the supplied evidence.

Do not automatically claim that there is
"no differentiation between verified and
unverified evidence" because the pipeline
tracks verification status.

Return ONLY valid JSON.

Required format:

{{
  "title": "Indian AI Startup Market Analysis",
  "executive_summary": "...",
  "market_overview": "...",
  "companies": [
    {{
      "company_name": "...",
      "overall_score": 0,
      "key_strengths": [],
      "key_risks": [],
      "evidence_summary": "..."
    }}
  ],
  "methodology": "...",
  "limitations": [],
  "validation": {{
    "status": "pending",
    "issues": [],
    "hallucination_check": false
  }}
}}
"""

    llm = get_llm()

    response = llm.invoke(
        prompt
    )

    usage = extract_usage(response)

    print(
        "Synthesizer LLM usage: "
        f"input={usage.input_tokens}, "
        f"output={usage.output_tokens}, "
        f"total={usage.total_tokens}, "
        f"cost=${usage.estimated_cost_usd:.4f}"
    )

    text = response.content

    if not text:

        print(
            "Synthesizer returned empty output."
        )

        return {
            "final_report": "",
            "total_input_tokens": usage.input_tokens,
            "total_output_tokens": usage.output_tokens,
            "total_tokens": usage.total_tokens,
            "total_cost_usd": usage.estimated_cost_usd,
        }

    text = text.strip()

    if text.startswith("```"):

        lines = text.splitlines()

        if lines:
            lines = lines[1:]

        if (
            lines
            and lines[-1].strip()
            == "```"
        ):
            lines = lines[:-1]

        text = "\n".join(
            lines
        ).strip()

    try:

        report = json.loads(
            text
        )

    except json.JSONDecodeError as error:

        print(
            "Synthesizer returned invalid JSON."
        )

        print(
            f"JSON parsing error: {error}"
        )

        return {
            "final_report": text,
            "total_input_tokens": usage.input_tokens,
            "total_output_tokens": usage.output_tokens,
            "total_tokens": usage.total_tokens,
            "total_cost_usd": usage.estimated_cost_usd,
        }

    # ------------------------------------------------------------
    # Preserve Python-generated scores exactly.
    # ------------------------------------------------------------

    score_lookup = {
        item["company_name"]:
            item["overall_score"]
        for item in state.company_scores
    }

    for company in report.get(
        "companies",
        [],
    ):

        company_name = company.get(
            "company_name",
            "",
        )

        if company_name in score_lookup:

            company["overall_score"] = (
                score_lookup[company_name]
            )

    print()
    print(
        "===== SCORE PRESERVATION CHECK ====="
    )

    for company in report.get(
        "companies",
        [],
    ):

        print(
            f"{company.get('company_name')}: "
            f"{company.get('overall_score')}"
        )

    print(
        "===================================="
    )

    return {
        "final_report": json.dumps(
            report,
            indent=2,
        ),
        "total_input_tokens": usage.input_tokens,
        "total_output_tokens": usage.output_tokens,
        "total_tokens": usage.total_tokens,
        "total_cost_usd": usage.estimated_cost_usd,
    }